name: Deploy to github pages

on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      fbsecrets: ${{ secrets.FBSECRETS }}
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - run: touch src/data/secrets.js
    - run: echo -e "$fbsecrets" > src/data/secrets.js
    - run: npm install
    - run: npm run deploy -- -m "Deployed site to github pages"
