name: Deploy to github pages

on:
  push:
    branches:
      - master
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      fbsecrets: ${{ secrets.FBSECRETS }}
    
    steps:
    - name: setup
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - run: touch src/data/secrets.js
    - run: echo -e "$fbsecrets" > src/data/secrets.js
    - run: npm install
    - run: |
       git config --global user.email "rchin@ualberta.ca"
       git config --global user.name "Autodeploy"
    
    - name: run deploy
    - run: CI=false npm run deploy -- -m "Deployed site to github pages"
