name: Deploy to github pages

on:
  push:
    branches:
      - master
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      fbsecrets: ${{ secrets.FBSECRETS }}
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - run: touch src/data/secrets.js
    - run: echo '$fbsecrets' > src/data/secrets.js
    - run: npm ci
    - run: |
       git config --global user.email "github-actions@github.com"
       git config --global user.name "github-actions"
    - run: CI=false npm run build
    - run : git --work-tree build add --all
    - run : git commit -m "Automatic Deploy action run by github-actions"
    - run : git push origin HEAD:gh-pages --force
